def mo_va_viet_tep_tin_nhi_phan()
    f = open(r'D:\data\While.drawio.png','r+b')
    with open(r'D:\data\While.drawio.png','r+b') as f:
        print(f.read(1))
        print(f.read(3))
        print(f.read(2))
        print(f.read(1))
        print(f.read(1))
    f.close()
    f = open(r'D:\data\While.drawio.png','w+b')
    sentence = bytearray("Python is easy to learn".encode("ascii"))
    f.write(sentence)
    f.close()
f = open(r'D:\data\While.drawio.png','r')
z = f.read()
print(z)
f.close()
